In [1]:
from scipy.stats import norm
from scipy.stats import t
import numpy as np
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm


Um fabricante de refrigerante anunciou que o índice de cafeína do seu refrigerante de cola é igual a 35mg por lata. Um laboratório realizou 20 análises do índice de cafeína obtendo os resultados (37, 34, 36, 37, 35, 32, 30, 35, 34, 36, 39, 38, 34, 35, 31, 30, 33, 35, 36, 31). Sabe-se que o índice de cafeína do refrigerante de cola dessa marca se distribui normalmente com variância igual a 4. Responda respectivamente a conclusão sobre o teste e o valor crítico para este teste com nível de significância de 5%? Utilize da suposição que queremos identificar se a média de cafeína caso não seja 35mg, seja maior que esse valor (caso unicaudal do teste)

In [2]:
from statsmodels.stats.weightstats import DescrStatsW

In [3]:
df = pd.DataFrame({'mg' : [37, 34, 36, 37, 35, 32, 30, 35, 34, 36, 39, 38, 34, 35, 31, 30, 33, 35, 36, 31]})

In [4]:
df


mg
0   37
1   34
2   36
3   37
4   35
5   32
6   30
7   35
8   34
9   36
10  39
11  38
12  34
13  35
14  31
15  30
16  33
17  35
18  36
19  31

In [5]:
n = len(df)
n

20

In [6]:
media_amostra = df.mean()
media_amostra

mg    34.4
dtype: float64

In [7]:
desvio_amostra = df.std()
desvio_amostra

mg    2.583347
dtype: float64

In [8]:

graus_de_liberdade = n - 1
u0 = 35
sigma = np.sqrt(4)
erro = sigma/np.sqrt(n)

In [9]:
confianca = 0.95
alpha = 0.05

In [10]:
from scipy.stats import t as t_student

In [11]:
t_alpha = t_student.isf(alpha, df=19)
t_alpha

1.7291328115213678

In [12]:
t = (media_amostra - u0) / (desvio_amostra/np.sqrt(n))
t

mg   -1.038684
dtype: float64

In [13]:
t <= t_alpha

mg    True
dtype: bool

In [14]:
pvalue = t_student.sf(t, df=graus_de_liberdade)
pvalue

#pvalue = t_student.cdf(-t, df=graus_de_liberdade)*2
#pvalue

array([0.84400486])

In [15]:
pvalue > alpha

array([ True])

In [16]:
teste = DescrStatsW(df['mg'])

In [17]:
teste = DescrStatsW(df['mg'])

In [18]:
teste.ttest_mean(value=u0, alternative='larger')

(-1.0386839525631981, 0.8440048606579256, 19.0)

In [19]:
teste.ttest_mean(value=u0, alternative='larger')[1]

0.8440048606579256

In [20]:
minimo = t_student.ppf(alpha, loc=35, scale=erro, df=19)
minimo

34.22670829826258

In [21]:
maximo = t_student.ppf(1-alpha, loc=35, scale=erro, df=19)
maximo

35.77329170173742

In [22]:
minimo < float(media_amostra) and float(media_amostra) < maximo

True

In [23]:
from scipy.stats import t as t_student

In [24]:
def new_data(media , sigma, z ):
    X = media + sigma * z
    return X

In [25]:
z_alpha = norm.isf(.05)
z_alpha

1.6448536269514729

In [26]:
#z = (media_amostra - u0) / (sigma / np.sqrt(n))
#z

In [27]:
z = (media_amostra - u0) / (desvio_amostra / np.sqrt(n))
z

mg   -1.038684
dtype: float64

In [35]:
#x_critico = new_data(35,erro,z_alpha) ou x(data maximo)
x_critico = new_data(35,erro,t_alpha)
x_critico

35.77329170173742

In [29]:
minimo = norm.ppf(alpha, loc=35, scale=erro)
minimo

34.26439909541988

In [30]:
pvalue = norm.sf(z)
pvalue

array([0.85052413])

In [31]:
from statsmodels.stats.weightstats import ztest

In [32]:
ztest(x1=df['mg'], value=u0, alternative='larger')

(-1.0386839525631981, 0.8505241265705443)

In [33]:
teste = DescrStatsW(df['mg'])

In [34]:
teste.ztest_mean(value=u0 ,alternative='larger' )

(-1.0386839525631981, 0.8505241265705443)